- name: Deploy Apache Docker Container
  hosts: localhost
  become: yes

  tasks:
    - name: Pull the latest Apache docker
      ansible.builtin.docker_image:
        name: httpd
        source: pull
        state: present

    - name: Run Apache container
      ansible.builtin.docker_container:
        name: apache2
        image: httpd:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - "/var/www/html:/usr/local/apache2/htdocs"
          