---
- name: Deploy FTP Docker Container
  hosts: web_servers
  become: yes  # Use sudo if necessary

  tasks:
    - name: Deploy an FTP Docker container
      ansible.builtin.docker_container:
        name: ftp_server
        image: fauria/vsftpd
        state: started
        published_ports:
          - "21:21"
        env:
          FTP_USER: 'user'
          FTP_PASS: 'pass'
          PASV_ADDRESS: 'localhost'
          PASV_MIN_PORT: '21100'
          PASV_MAX_PORT: '21110'
        volumes:
          - "ftp_data:/var/lib/ftp"
          - "ftp_config:/etc/vsftpd"
        restart_policy: always